config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [ :show, :edit, :update ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :games, only: [:index, :show, :new, :create, :destroy] do
    resources :bookings, only: [:index, :show, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :game
  belongs_to :user

end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :bookings, :dependent => :delete_all

  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode

  include PgSearch::Model

  pg_search_scope :search_by_title_and_description,
    against: [ :title, :description ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }



end

app/models/user.rb
class User < ApplicationRecord
  attr_writer :login

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
  :validatable, authentication_keys: [:login]

  validates :username, presence: true, uniqueness: { case_sensitive: false }


  has_many :games, :dependent => :delete_all
  has_many :bookings, :dependent => :delete_all

  has_one_attached :photo


  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :authenticate_user!

  def index
  end

  def show
  end

  def new
    @game = Game.find(params[:game_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @game = Game.find(params[:game_id])
    @booking = Booking.new(booking_params)

    @booking.game = @game
    @booking.user = current_user

    authorize @booking

    @count = 0


    if @game.bookings.present?

      @game.bookings.each do |booking|
        if @booking.booking_start < booking.booking_start && @booking.booking_end < booking.booking_start || @booking.booking_start  > booking.booking_end
          true
          @count += 1
          if @count == @game.bookings.length
            @booking.save
          end
        else
          flash.alert = "This game is unavailable to rent during your proposed dates. Please choose another set of dates."
        end
      end
    else
      @booking.save

    end

    redirect_to game_path(@game)
  end

  private

  def booking_params
    params.require(:booking).permit(:booking_start, :booking_end)
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_action :authenticate_user!

  def index

    @games = policy_scope(Game)

    if params["title"].present?
      @search = params["title"]
      @title = @search["item"]

      if @title.present?

        @games = Game.search_by_title_and_description(@title)
      else
        @games = Game.all
      end
    else
      @games = Game.all
    end
  end

  def show
    @game = Game.find(params[:id])
    authorize @game
    @booking = @game.bookings.new

    @marker = {
        lat: @game.latitude,
        lng: @game.longitude
              }

  end

  def new
    @game = Game.new
    authorize @game
  end

  def create
    @game = Game.new(game_params)
    authorize @game

    @game.user = current_user

    if @game.save
      redirect_to game_path(@game)
    else
      render :new
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    authorize @game

    redirect_to user_path(@game.user)
  end

  private

  def game_params
    params.require(:game).permit(:title, :description, :availability, :address, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home


  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    authorize @user

    if @user.save
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/bookings/new.html.erb
<div class="container">
  <h1>Book this game</h1>
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">

      <%= simple_form_for [ @game, @booking ] do |f| %>
        <%= f.input :booking_start, as: :string, required: false, input_html: {class: "start_date"} %>
        <%= f.input :booking_end, as: :string, required: false, input_html: {class: "end_date"} %>
        <%= f.button :submit, "Go", class: "btn" %>
      <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/games/create.html.erb
<h1>Games#create</h1>
<p>Find me in app/views/games/create.html.erb</p>

app/views/games/index.html.erb
<div class="container index">
  <div class="col-xs-auto">
    <h1>Games</h1>
    <div class="row col-xs-12">
      <% @games.each do |game| %>
      <div class="col col-xs-12 col-sm-12 col-md-6 col-lg-4">
        <% @img = cloudinary_url(game.photo.key) if game.photo.present? %>
        <% @card_title = link_to(game.title, game_path(game)) %>
        <% @card_address = game.address %>
        <% @card_description = game.description %>
        <% @card_owner = game.user.username %>
        <%= render 'shared/card' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/games/new.html.erb
<div class="container">
  <h1>Add a Game</h1>

  <%= simple_form_for(@game) do |f| %>
    <div class="actions form-group">
      <%= f.input :title, class: "form-control" %>
      <%= f.input :description, class: "form-control" %>
      <%= f.input :address, class: "form-control" %>
      <%= f.input :photo, as: :file  %>


      <%= f.submit class: 'btn margin-top' %>
    </div>
  <% end %>

</div>

app/views/games/show.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cloudinary_url(@game.photo.key)%>)">
  <h1><%= @game.title %></h1>
</div>
<div class="card-product-infos">
<div class="container">
  <div class="d-flex flex-row">
    <div class="col-xl">
      <div class="d-inline-flex p-1 col-5">
        <div>
          <h3>Game description:</h3>
          <p><%= @game.description %></p>
        </div>
      </div>
      <div class="d-inline-flex p-2 col-4">
        <div>
          <h3>Game Owner:</h3>
          <p><%= @game.user.username %></p>
        </div>
      </div>
      <div class="d-inline-flex p-3 col-auto">
        <div>
          <h3>Address:</h3>
          <p><%= @game.address %></p>
        </div>
      </div>
      <!-- <h2>Game availability:</h2>
      <p><%= @game.availability %></p> -->


      <div class="box">
        <div class="box-row">
          <div class="box-cell box1">
            <h4 style="text-align:center;">Game Pick-up Location</h4>
            <div id="map"
                 style="width: 500px; height: 400px;"
                 data-markers="<%= @marker.to_json %>"
                 data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">

            </div>
          </div>

          <div class="box-cell box2">
            <div>
            <br>
            <% if current_user != @game.user %>

              <div class="form-wrapper" style="width: 400px; margin: 0 auto;">

                <%= simple_form_for [ @game, @booking ] do |f| %>
                  <%= f.input :booking_start, as: :string, required: false, input_html: {class: "start_date"} %>
                  <%= f.input :booking_end, as: :string, required: false, input_html: {class: "end_date"} %>
                  <%= f.button :submit, "Book this game", class: "btn" %>
                <% end %>
                <br>
                <h4 style="text-align:center;">Current bookings:</h4>
                <% @game.bookings.each do |booking| %>
                  <% if booking.id.present? %>
                  <p>Booked by: <%= booking.user.username %> </p>
                  <p>Booking start date: <%= booking.booking_start %> </p>
                  <p>Booking end date: <%= booking.booking_end %> </p>
                  <% end %>
                <% end %>
              </div>

          <!-- <button class="btn btn-outline-primary" type="submit"><%= link_to "Rent this game", new_game_booking_path(@game) %></button> -->
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameRent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

  </head>

  <body style="background: #F2F2F2;">

    <%= render 'shared/flashes' %>


    <%= render 'shared/navbar' %>

    <div style="padding-top: 20px; min-height: 75vh;">

      <%= yield %>
    </div>
    <%= render 'shared/footer' %>

    <%= javascript_pack_tag 'application' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
  </body>

</html>

app/views/pages/home.html.erb
<div class="main" style="margin-top: -20px">
  <div>
    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/776092/pexels-photo-776092.jpeg)">
      <div style="display: inline;">
        <h1 style="margin:1em 0 2em 0;"><strong>Welcome to Game Rent!</strong></h1>
        <h2>Don't buy, but <strong>rent</strong> your favorite games!</h2>
      </div>
    </div>
  </div>

  <div class="row col-xs-12 col-lg-12 d-flex justify-content-between mx-auto">
    <div class="p-2 col col-xs-12 col-sm-6 col-md-4">
      <div>
        <img class="homimg" src= "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg" />
      </div>
      <div>
        <p><strong>Super fun games</strong></p>
      </div>
    </div>
    <div class="p-2 col col-xs-12 col-sm-6 col-md-4">
      <div>
        <img class="homimg" src="https://images.pexels.com/photos/209728/pexels-photo-209728.jpeg" />
      </div>
      <div>
        <p><strong>Shared by fellow gamers</strong></p>
      </div>
    </div>
    <div class="p-2 col col-xs-12 col-sm-6 col-md-4">
      <div>
        <img class="homimg" src="https://cdn.pixabay.com/photo/2020/02/14/18/23/approval-4849109_1280.jpg" />
      </div>
      <div>
        <p><strong>User-friendly</strong></p>
      </div>
    </div>
    <div class="col col-xs-12 col-sm-12 col-md-12">
      <div>
        <img class="homimg" src="https://cdn.pixabay.com/photo/2017/04/09/12/00/gaming-2215601_1280.jpg" />
      </div>
      <div>
        <p><strong>Cross-platform</strong></p>
      </div>
    </div>
  </div>

  <div class="row align-items-center h-100">
    <div class="small_box my-auto">

      <h3><strong>What you have access to</strong></h3>
      <p>+10,000 games</p>
      <p>+398 users' posts and recommendations</p>
      <p>Games near <strong>you</strong></p>

    </div>
      <div class="small_box justify-content-center align-self-center my-auto">
        <% if user_signed_in? %>
          <h3>
            <button class="btn"><a href="#"><%= link_to "Dashboard", user_path(current_user), class: "nav-link nbtn" %></a></button>
            <button class="btn"><a href="#"><%= link_to "See all Games", games_path, class: "nav-link" %></a></button>
            <p style="margin-top: 25px;" >Feel free to checkout our large selection of games</p>
          </h3>

        <% else %>
          <h3>
            <p>You haven't joined Game Rent yet?</p>
            <p>Start today!</p>
          </h3>
          <div><%= link_to "Sign up", new_user_registration_path, class: "btn" %></div>
          <%#= link_to "Log in", new_user_session_path, class: "btn" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="bottom">

    <div class="row col-xs-12 col-lg-12 d-flex justify-content-between mx-auto">

      <div class="p-3 col col-xs-12 col-sm-6 col-md-4">
        <img class="homimg" src= "https://res.cloudinary.com/dsgl1xjqn/image/upload/v1613474356/2_3_gluvh3.jpg" />
      </div>
      <div class="p-3 col col-xs-12 col-sm-6 col-md-4">
        <img class="homimg" src="https://res.cloudinary.com/dsgl1xjqn/image/upload/v1613474356/2_4_x2ghxi.jpg" />
      </div>
      <div class="p-3 col col-xs-12 col-sm-6 col-md-4">
        <img class="homimg" src= "https://res.cloudinary.com/dsgl1xjqn/image/upload/v1613474356/2_1_qqct4z.jpg" />
      </div>

      <div class="p-3 col col-xs-12 col-sm-6 col-md-4">
        <img class="homimg" src="https://res.cloudinary.com/dsgl1xjqn/image/upload/v1613474356/2_2_yspaj5.jpg" />
      </div>
      <div class="p-3 col col-xs-12 col-sm-6 col-md-4">
          <img class="homimg" src= "https://res.cloudinary.com/dsgl1xjqn/image/upload/v1613471812/1_beyhaz.png" />
      </div>
      <div class="p-3 col col-xs-12 col-sm-6 col-md-4">
          <img class="homimg" src="https://res.cloudinary.com/dsgl1xjqn/image/upload/v1613472432/2_adpne2.png" />
      </div>

      <div class="p-3 col col-xs-12 col-sm-6 col-md-4">
        <img class="homimg" src="https://res.cloudinary.com/dsgl1xjqn/image/upload/v1613472433/3_x71keo.png" />
      </div>
      <div class="p-3 col col-xs-12 col-sm-6 col-md-4">
        <img class="homimg" src="https://res.cloudinary.com/dsgl1xjqn/image/upload/v1613472433/4_zy1yx8.png" />
      </div>
      <div class="p-3 col col-xs-12 col-sm-6 col-md-4">
        <img class="homimg" src="https://data4.origin.com/asset/content/dam/originx/web/app/programs/About/aboutorigin_3840x2160_battlefield1.jpg/27051ac9-d3c0-49e3-9979-3dc1058a69f5/original.jpg" />
      </div>

    </div>

  </div>

app/views/shared/_card.html.erb
<div class="card-product">
  <%#= game.photo.attached? ? (cl_image_tag game.photo.key) : false %>
  <img src="<%= @img %>" >
  <div class="card-product-infos text-left">
    <h2 class="truncated" style="text-overflow: ellipsis;"><%= @card_title %></h2>
    <p class="truncated" style="text-overflow: ellipsis;"><%= @card_description %></p>
    <p class="truncated" style="text-overflow: ellipsis;">Address: <%= @card_address %></p>
    <p class="truncated" style="text-overflow: ellipsis;">Game Owner: <%= @card_owner %></p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-basic">
  <footer>
    <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Home</a></li>
      <li class="list-inline-item"><a href="#">Services</a></li>
      <li class="list-inline-item"><a href="#">About</a></li>
      <li class="list-inline-item"><a href="#">Terms</a></li>
      <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
    </ul>
    <p class="copyright">Company Name © 2018</p>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<% if current_user.present? %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="justify-content: space-between;">
<% else %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="justify-content: flex-end;">
<% end %>
  <% if current_user.present? %>
    <a class="navbar-brand" href="/">
        <%= image_tag "console.png" %>
    </a>
  <% end %>
  <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> -->
  <div>
    <ul class="navbar-nav mr-auto">
      <% if current_user.present? %>
        <li class="nav-item active">
          <button type="button" class="btn"><%= link_to "Add a Game", new_game_path, class: "nav-link nbtn" %></button>
        </li>
      <% end %>
      <% if current_user.present? %>
        <li class="nav-item active">
          <button type="button" class="btn"><%= link_to "See all Games", games_path, class: "nav-link nbtn" %></button>
        </li>
      <% end %>
      <% if current_user.present?  %>
        <li><%= render 'shared/searchbar' %></li>
      <% end %>
      <% if current_user.present? %>
      <% end %>
      <% if current_user %>
        <li class="nav-item active">
          <%= link_to "Dashboard", user_path(current_user), class: "nav-link nbtn" %>
        </li>
      <% end %>
      <% if current_user.present?  %>
        <li class="nav-item active">
          <%= link_to "Log out", destroy_user_session_path, :method => :delete, class: "nav-link nbtn" %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Log in", new_user_session_path, class: "nav-link nbtn" %>
        </li>
      <% end %>
      <% if !current_user.present?  %>
        <li class="nav-item active">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link nbtn" %>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <% if current_user %>
          <% if current_user.photo.attached? %>
            <%= image_tag cloudinary_url(current_user.photo.key), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://cdn2.vectorstock.com/i/thumb-large/23/81/default-avatar-profile-icon-vector-18942381.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
        <% else %>
          <%= image_tag "https://cdn2.vectorstock.com/i/thumb-large/23/81/default-avatar-profile-icon-vector-18942381.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <!-- <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div> -->
      </li>
    </ul>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<%= simple_form_for :title, url: games_path, method: "GET", html: { class: 'form-inline' } do |f| %>
  <%= f.input :item, input_html: {value: ""}, label: false %>
  <%= f.submit "Search", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <h1>Add an avatar picture</h1>

  <%= simple_form_for(@user) do |f| %>
    <div class="actions form-group">
      <%= f.input :photo, as: :file  %>


      <%= f.submit class: 'btn margin-top' %>
    </div>
  <% end %>

</div>

app/views/users/show.html.erb
<div class="container">
    <div class="user-dashboard">
      <div class="d-flex space-between">
          <div class="col-md-6 col-sm-6 col-xs-12">
            <h1> <strong>Hello, <%= @user.username %></strong> </h1>
            <button style="margin-bottom: 20px" type="button" class="btn btn-sm"><%= link_to "Add/edit my avatar pic", edit_user_path(@user) %></button>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12 text-right">
            <h2><strong><u>My Login Details</u></strong></h2>
            <h3><%= @user.email %> </h3>
          </div>
      </div>
      <hr>
      <div class="row" style="padding-top: 20px">
        <div class="col-md-6 col-sm-6 col-xs-12 my-games">
            <div class="dashboard text-left">
                <h3 style="padding-bottom: 20px">My Games</h3>
                  <% @user.games.each do |game| %>
                    <% @img = cloudinary_url(game.photo.key) if game.photo.present? %>                      <% @card_title = link_to(game.title, game_path(game)) %>
                    <% @card_description = game.description %>
                    <% @card_owner = game.user.username %>
                    <% @card_address = game.address %>
                    <%= render 'shared/card' %>
                    <button type="button" class="btn btn-sm"><%= link_to "Delete this game posting", game_path(game), data: { method: :delete, confirm: "Are you sure?" }  %> </button>
                    <hr>

                  <% end %>
            </div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12 renting">
              <div class="dashboard text-right">
                <h3 style="padding-bottom: 20px">Games I'm Renting</h3>
                <% if @user.bookings.present? %>
                    <% @user.bookings.each do |booking| %>

                      <% @img = cloudinary_url(booking.game.photo.key) %>
                      <% @card_title = link_to(booking.game.title, game_path(booking.game)) %>
                      <% @card_description = booking.game.description %>
                      <% @card_owner = booking.game.user.username %>
                      <% @card_address = booking.game.address %>

                      <%= render 'shared/card' %>
                      <p> <strong>Rent period: </strong>  <%= booking.booking_start %> : <%= booking.booking_end %> </p>
                      <hr>
                    <% end %>
                <% else %>
                  <%= link_to "Go rent some games!", games_path, class: "nav-link btn games-path" %>
                <% end %>
              </div>
          </div>
      </div>
    </div>




</div>